CREATE TABLE "studentData" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_name" TEXT REFERENCES "user"(user_name)
    ON DELETE CASCADE,
  "queue_id" INTEGER REFERENCES "queue"(id),
  "helped_by" TEXT DEFAULT NULL,
  "question" TEXT NOT NULL,
  "note" TEXT DEFAULT NULL
);